// Dependency-free browser smoke test using Chrome DevTools Protocol; Node.js 22+.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawn,execFileSync} from 'node:child_process';import {pathToFileURL,fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),profile=fs.mkdtempSync(path.join(os.tmpdir(),'university-atlas-test-'));
const errors=[],network=[],wait=ms=>new Promise(r=>setTimeout(r,ms));let proc,ws;
async function main(){
 const chrome=process.env.CHROME_BIN||execFileSync('which',['google-chrome'],{encoding:'utf8'}).trim();
 proc=spawn(chrome,['--headless','--disable-gpu','--disable-background-networking','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
 const portFile=path.join(profile,'DevToolsActivePort');for(let i=0;i<300&&!fs.existsSync(portFile);i++)await wait(100);if(!fs.existsSync(portFile))throw Error('Chrome DevTools startup failed');
 const port=fs.readFileSync(portFile,'utf8').split('\n')[0],tabs=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json(),tab=tabs.find(t=>t.type==='page');
 ws=new WebSocket(tab.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject});let seq=0;const pending=new Map();
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Network.requestWillBeSent'&&/^https?:/.test(m.params.request.url))network.push(m.params.request.url);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 await send('Runtime.enable');await send('Page.enable');await send('Network.enable');await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:pathToFileURL(path.join(ROOT,'dist/china-university-atlas.html')).href});
 let ready=false;for(let i=0;i<300;i++){await wait(100);if(await evaluate('!!window.__atlas')){ready=true;break;}}if(!ready)throw Error('Atlas did not boot');
 const result=await evaluate('__atlas.selfTest()');
 const v52=await evaluate(`({associationCount:__atlas.D.districtAssociations.length,linyiDistrict:__atlas.schoolRows('山东省','临沂市','河东区').some(u=>u.u==='临沂工学院'&&u.associations.length>0),taiyuanExact:__atlas.schoolRows('山西省','太原市','尖草坪区').some(u=>u.u==='太原卫生职业学院'&&u.campuses.some(c=>c.verified)),fakeAssociationPrecision:__atlas.D.districtAssociations.some(a=>'lng' in a||'lat' in a||'address' in a),cqCorrect:__atlas.D.districtAssociations.some(a=>a.u==='重庆城乡发展职业学院'&&a.d==='云阳县'&&a.verified)&&__atlas.D.districtAssociations.some(a=>a.u==='重庆中药职业学院'&&a.d==='涪陵区'&&a.verified)&&!__atlas.D.districtAssociations.some(a=>a.u==='重庆城乡发展职业学院'&&a.d==='南岸区'),scCorrect:__atlas.schoolRows('四川省','成都市','彭州市').some(u=>u.u==='四川中医药职业学院'&&u.campuses.some(c=>c.verified))&&!__atlas.D.districtAssociations.some(a=>a.u==='四川中医药职业学院'&&a.d==='龙泉驿区')})`);
 await evaluate(`document.getElementById('includeBranch').checked=true;__atlas.navigateID('440000')`);const shenzhen=await evaluate(`(()=>{const f=__atlas.S.geo.find(x=>x.name==='深圳市'),b=best(f),a=D.cityAffiliates['广东省|深圳市'],labelOn=cityDisplayUniversity(f,b);document.getElementById('includeBranch').checked=false;const labelOff=cityDisplayUniversity(f,b);document.getElementById('includeBranch').checked=true;return{feature:{id:f.id,level:f.level},node:{kind:current().kind,p:current().p},main:b.rawU||b.u,labelOn,labelOff,localOnly:localCityRows('广东省','深圳市').every(u=>u.c==='深圳市'),ug:a.undergraduate.map(x=>x.parent),grad:a.graduate.map(x=>x.parent),tierLabels:affiliateLines(a).map(x=>x.label),bundleVisible:cityAffiliatesVisible(f)}})()`);
 await evaluate(`document.getElementById('includeBranch').checked=true;__atlas.navigateID('320000')`);const suzhou=await evaluate(`(()=>{const f=__atlas.S.geo.find(x=>x.name==='苏州市'),b=best(f),a=D.cityAffiliates['江苏省|苏州市'];return{main:b.rawU||b.u,labelOn:cityDisplayUniversity(f,b),ug:a.undergraduate.map(x=>x.name),hasNju:a.undergraduate.some(x=>x.parent==='南京大学'),bundleVisible:cityAffiliatesVisible(f)}})()`);
 const v53={shenzhen,suzhou};result.v52=v52;result.v53=v53;result.browserNetworkOffline=true;result.httpRequests=network;result.runtimeErrors=errors;
 const cityOK=shenzhen.localOnly&&shenzhen.main&&!['哈尔滨工业大学','中山大学','暨南大学','清华大学','北京大学'].includes(shenzhen.main)&&shenzhen.labelOn.endsWith('＋')&&!shenzhen.labelOff.endsWith('＋')&&shenzhen.bundleVisible&&shenzhen.ug.includes('哈尔滨工业大学')&&shenzhen.grad.includes('清华大学')&&shenzhen.grad.includes('北京大学')&&shenzhen.tierLabels.join('|')==='本科校区 / 分校|研究生院 / 研究院'&&suzhou.main==='苏州大学'&&suzhou.labelOn.endsWith('＋')&&suzhou.bundleVisible&&suzhou.hasNju;
 result.pass=result.pass&&!network.length&&!errors.length&&v52.associationCount===33&&v52.linyiDistrict&&v52.taiyuanExact&&!v52.fakeAssociationPrecision&&v52.cqCorrect&&v52.scCorrect&&cityOK;result.artifact='dist/china-university-atlas.html';
 fs.writeFileSync(path.join(ROOT,'reports/offline-browser-test.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
 for(const [name,id,width,height]of [['national-desktop.png','100000',1440,1000],['guangdong-city-layer.png','440000',1440,1000],['jiangsu-city-layer.png','320000',1440,1000],['hangzhou-desktop.png','330100',1440,1000],['linyi-hedong-evidence.png','371312',1440,1000],['national-mobile.png','100000',390,844]]){await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<500});await evaluate(`document.getElementById('includeBranch').checked=true;__atlas.navigateID('${id}')`);await wait(400);const shot=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(ROOT,'docs',name),Buffer.from(shot.data,'base64'));}
 await send('Browser.close').catch(()=>{});ws.close();if(!result.pass)throw Error('Offline test failed');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>{if(ws)ws.close();if(proc)proc.kill();setTimeout(()=>fs.rmSync(profile,{recursive:true,force:true}),500);});
