// V5.9 interaction gate: zero leaders, screen-stable type and deferred label layout.
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawn,execFileSync} from 'node:child_process';import {pathToFileURL,fileURLToPath} from 'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),profile=fs.mkdtempSync(path.join(os.tmpdir(),'atlas-premium-')),wait=ms=>new Promise(r=>setTimeout(r,ms));let proc,ws;
async function main(){
 const chrome=process.env.CHROME_BIN||execFileSync('which',['google-chrome'],{encoding:'utf8'}).trim();
 proc=spawn(chrome,['--headless','--disable-gpu','--disable-background-networking','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
 const pf=path.join(profile,'DevToolsActivePort');for(let i=0;i<300&&!fs.existsSync(pf);i++)await wait(100);if(!fs.existsSync(pf))throw Error('Chrome startup failed');
 const port=fs.readFileSync(pf,'utf8').split('\n')[0],tabs=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json(),tab=tabs.find(t=>t.type==='page');
 ws=new WebSocket(tab.webSocketDebuggerUrl);await new Promise((ok,no)=>{ws.onopen=ok;ws.onerror=no});let seq=0;const pending=new Map(),http=[],errors=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);else if(m.method==='Network.requestWillBeSent'&&/^https?:/.test(m.params.request.url))http.push(m.params.request.url);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
 const evaljs=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 await send('Runtime.enable');await send('Page.enable');await send('Network.enable');await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});await send('Emulation.setDeviceMetricsOverride',{width:1440,height:900,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:pathToFileURL(path.join(ROOT,'dist/china-university-atlas.html')).href});let ready=false;for(let i=0;i<300;i++){await wait(100);if(await evaljs('!!window.__atlas&&!!window.__premium')){ready=true;break;}}if(!ready)throw Error('Premium atlas did not boot');await wait(220);
 const before=await evaljs(`(()=>{__premium.setDrawer(false);const g=document.querySelector('#labelLayer g[data-label-id="650000"]')||document.querySelector('#labelLayer g[data-label-id]'),t=g?.querySelector('text');return{metrics:{...__premiumMetrics},leaders:document.querySelectorAll('#labelLayer .leader').length,font:t?Number(t.getAttribute('font-size')):null,labelId:g?.getAttribute('data-label-id')||null,scale:document.querySelector('.premium-scale-label')?.textContent||'',drawer:document.querySelector('.side')?.classList.contains('premium-open'),button:!!document.getElementById('premiumPanelBtn')};})()`);
 await evaljs(`(()=>{const m=document.getElementById('map'),r=m.getBoundingClientRect();for(let i=0;i<48;i++)m.dispatchEvent(new WheelEvent('wheel',{deltaY:-7,clientX:r.left+r.width*.52,clientY:r.top+r.height*.50,bubbles:true,cancelable:true}));return true;})()`);await wait(70);
 const during=await evaljs(`(()=>({metrics:{...__premiumMetrics},leaders:document.querySelectorAll('#labelLayer .leader').length,zooming:document.body.classList.contains('premium-zooming')}))()`);await wait(260);
 const after=await evaljs(`(()=>{const g=document.querySelector('#labelLayer g[data-label-id="${before.labelId||''}"]'),t=g?.querySelector('text');return{metrics:{...__premiumMetrics},leaders:document.querySelectorAll('#labelLayer .leader').length,font:t?Number(t.getAttribute('font-size')):null,scale:document.querySelector('.premium-scale-label')?.textContent||'',zooming:document.body.classList.contains('premium-zooming')};})()`);
 const layoutDuring=during.metrics.layoutCount-before.metrics.layoutCount,layoutAfter=after.metrics.layoutCount-before.metrics.layoutCount,fontRatio=before.font&&after.font?after.font/before.font:null;
 const checks={zeroLeaderBefore:before.leaders===0,zeroLeaderDuring:during.leaders===0,zeroLeaderAfter:after.leaders===0,noLayoutDuringWheel:layoutDuring===0,oneIdleLayout:layoutAfter>=1&&layoutAfter<=1,wheelCoalesced:during.metrics.wheelFrames<during.metrics.wheelEvents,scalePresent:!!before.scale&&!!after.scale,drawerDefaultClosed:before.drawer===false,drawerButton:before.button,fontStable:fontRatio===null||(fontRatio>.92&&fontRatio<1.08),offline:http.length===0,runtimeClean:errors.length===0};
 const result={pass:Object.values(checks).every(Boolean),checks,before,during,after,layoutDuring,layoutAfter,fontRatio:fontRatio===null?null:Number(fontRatio.toFixed(3)),httpRequests:http,runtimeErrors:errors,artifact:'dist/china-university-atlas.html'};
 fs.writeFileSync(path.join(ROOT,'reports/premium-interaction.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));await send('Browser.close').catch(()=>{});if(!result.pass)throw Error('Premium interaction test failed');
}
main().catch(e=>{console.error(e.message);process.exitCode=1}).finally(()=>{if(ws)ws.close();if(proc)proc.kill();setTimeout(()=>{try{fs.rmSync(profile,{recursive:true,force:true})}catch{}},400)});
