
'use strict';
const D=JSON.parse(document.getElementById('schoolData').textContent), manifest=JSON.parse(document.getElementById('manifest').textContent);
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',palette=['#b9d6e6','#ceddb5','#f2d49f','#cbbce0','#edc4ca','#b8dbd3','#efc9a8','#c4d3e8'];
const root={id:'100000',name:'全国',kind:'country',p:'',c:'',d:''},S={stack:[root],geo:[],z:1,x:0,y:0,w:900,h:650,base:[],mapToken:0,labels:[],running:false,cancel:false,errors:[],complete:!!manifest.complete};
let CACHE={},busy=new Map(),controllers=new Set(),searchIndex=[],toastTimer,drawFrame,hoverId=null;const decoded=new Map();
const E=(tag,at={},txt)=>{const el=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(at))el.setAttribute(k,String(v));if(txt!==undefined)el.textContent=txt;return el;};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>S.stack[S.stack.length-1];
function short(s){return s.replace(/壮族自治区|回族自治区|维吾尔自治区|特别行政区|自治区|省$/g,'').replace(/(北京|天津|上海|重庆)市$/,'$1');}
function decodeLine(str){let p=0,x=0,y=0,out=[];function read(){let v=0,n=0,b;do{b=str.charCodeAt(p++)-63;v|=(b&31)<<n;n+=5;}while(b>=32&&p<str.length);return v&1?-(v+1)/2:v/2;}while(p<str.length){x+=read();y+=read();out.push([x/1000,y/1000]);}return out;}
function feature(a){const id=String(a[0]);const key=id+':'+a[5].length+':'+a[5].reduce((s,r)=>s+r.length,0);if(decoded.has(key))return decoded.get(key);const f={id,name:a[1],cp:a[2],level:a[3],n:a[4],rings:a[5].map(decodeLine)};decoded.set(key,f);return f;}
function encodeLine(points){let x=0,y=0,s='';for(const p of points){if(!Array.isArray(p)||!Number.isFinite(p[0])||!Number.isFinite(p[1]))throw Error('无效边界坐标');const a=Math.round(p[0]*1000),b=Math.round(p[1]*1000);for(const delta of[a-x,b-y]){let n=delta<0?-delta*2-1:delta*2;while(n>=32){s+=String.fromCharCode((32|(n&31))+63);n>>=5;}s+=String.fromCharCode(n+63);}x=a;y=b;}return s;}
function compact(g){if(!g||!Array.isArray(g.features)||!g.features.length)throw Error('不是有效的边界文件');const rows=g.features.filter(f=>f.geometry).map(f=>{const p=f.properties||{},v=f.geometry,polys=v.type==='Polygon'?[v.coordinates]:v.type==='MultiPolygon'?v.coordinates:[];return[p.adcode||0,p.name||'',p.centroid||p.center||null,p.level||'',p.childrenNum||0,polys.flat().filter(r=>r.length>=3).map(encodeLine)];});if(!rows.length||!rows.some(a=>a[5].length))throw Error('边界文件没有可绘制的多边形');return rows;}
const deg=Math.PI/180,phi1=25*deg,phi2=47*deg,n=Math.log(Math.cos(phi1)/Math.cos(phi2))/Math.log(Math.tan(Math.PI/4+phi2/2)/Math.tan(Math.PI/4+phi1/2)),F=Math.cos(phi1)*Math.pow(Math.tan(Math.PI/4+phi1/2),n)/n,rho0=F/Math.pow(Math.tan(Math.PI/4+35*deg/2),n);
function project(p){const lat=Math.max(-80,Math.min(80,p[1]))*deg,rho=F/Math.pow(Math.tan(Math.PI/4+lat/2),n),theta=n*(p[0]-105)*deg;return[rho*Math.sin(theta),rho*Math.cos(theta)-rho0];}
function polygonArea(r){let a=0;for(let i=0,j=r.length-1;i<r.length;j=i++)a+=r[j][0]*r[i][1]-r[i][0]*r[j][1];return Math.abs(a/2);}
function inRing(pt,r){let yes=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if((a[1]>pt[1])!==(b[1]>pt[1])&&pt[0]<(b[0]-a[0])*(pt[1]-a[1])/(b[1]-a[1])+a[0])yes=!yes;}return yes;}
function labelPoint(f){const rings=f.rings.filter(r=>r.length>3);if(!rings.length)return f.cp||[105,35];let main=rings.reduce((a,b)=>polygonArea(a)>polygonArea(b)?a:b);if(f.cp&&inRing(f.cp,main))return f.cp;let lo=[Infinity,Infinity],hi=[-Infinity,-Infinity];for(const p of main){lo[0]=Math.min(lo[0],p[0]);lo[1]=Math.min(lo[1],p[1]);hi[0]=Math.max(hi[0],p[0]);hi[1]=Math.max(hi[1],p[1]);}const center=[(lo[0]+hi[0])/2,(lo[1]+hi[1])/2];if(inRing(center,main))return center;let best=main[0],dist=Infinity;for(let i=1;i<15;i++)for(let j=1;j<15;j++){const p=[lo[0]+(hi[0]-lo[0])*i/15,lo[1]+(hi[1]-lo[1])*j/15],d=(p[0]-center[0])**2+(p[1]-center[1])**2;if(d<dist&&inRing(p,main)){best=p;dist=d;}}return best;}
function cityForDistrict(p,d){if(['北京市','天津市','上海市','重庆市'].includes(p))return p;for(const[k,ds]of Object.entries(D.districts))if(k.startsWith(p+'|')&&ds.includes(d))return k.split('|')[1];return p;}
function locationFor(f,node=current()){if(node.kind==='country')return{p:f.name,c:'',d:''};if(node.kind==='province'){if(f.level==='city')return{p:node.p,c:f.name,d:''};if(['北京市','天津市','上海市','重庆市','香港特别行政区','澳门特别行政区'].includes(node.p))return{p:node.p,c:cityForDistrict(node.p,f.name),d:f.name};return{p:node.p,c:f.name,d:f.name};}return{p:node.p,c:node.c,d:node.kind==='district'?node.d:f.name};}
function toast(text,ms=4000){clearTimeout(toastTimer);$('mapToast').textContent=text;$('mapToast').style.display='block';if(ms)toastTimer=setTimeout(()=>$('mapToast').style.display='none',ms);}
function enter(f){if(S.loading)return;if(!f.name||f.id==='0'||f.id.includes('JD'))return;const v=current();if(v.loadError){delete v.loadError;renderView();return;}if(v.kind==='district'){toast(f.name+' 已是当前最细地图层级');return;}if(v.noChildren){toast('当前数据源没有该地区进一步细分边界');return;}const l=locationFor(f,v);let kind=v.kind==='country'?'province':(v.kind==='province'&&f.level==='city'?'city':'district');const noChildren=kind==='city'&&!f.n;S.stack.push({id:f.id,name:f.name,kind,...l,f,noChildren});renderView();}
function back(){if(S.stack.length>1){S.stack.pop();renderView();}}
function regionColors(fs){
 const graph=fs.map(()=>new Set()),owner=new Map();
 fs.forEach((f,i)=>{for(const r of f.rings)for(const p of r){const key=Math.round(p[0]*1000)+','+Math.round(p[1]*1000);if(!owner.has(key))owner.set(key,new Set());for(const j of owner.get(key)){if(i!==j){graph[i].add(j);graph[j].add(i);}}owner.get(key).add(i);}});
 const result=fs.map(()=>-1),order=fs.map((_,i)=>i).sort((a,b)=>graph[b].size-graph[a].size);
 for(const i of order){const used=new Set([...graph[i]].map(j=>result[j]).filter(k=>k>=0));let choice=i%palette.length;for(let k=0;k<palette.length;k++){const c=(i+k)%palette.length;if(!used.has(c)){choice=c;break;}}result[i]=choice;}
 return result.map(i=>palette[i]);
}
function drawMap(reset=false){const rect=$('map').getBoundingClientRect();S.w=rect.width;S.h=rect.height;$('map').setAttribute('viewBox',`0 0 ${S.w} ${S.h}`);$('clipRect').setAttribute('width',S.w);$('clipRect').setAttribute('height',S.h);if(reset){S.z=1;S.x=S.y=0;}const nation=current().kind==='country',projected=[];let xmin=Infinity,ymin=Infinity,xmax=-Infinity,ymax=-Infinity;for(const f of S.geo){const rings=f.rings.map(r=>r.map(project));projected.push(rings);f.rings.forEach((r,ri)=>r.forEach((p,pi)=>{if(nation&&(p[1]<18||!f.name))return;const q=rings[ri][pi];xmin=Math.min(xmin,q[0]);xmax=Math.max(xmax,q[0]);ymin=Math.min(ymin,q[1]);ymax=Math.max(ymax,q[1]);}));}if(!Number.isFinite(xmin))return;const top=126,bottom=55,left=nation?30:38,right=nation?72:48,scale=Math.min((S.w-left-right)/Math.max(xmax-xmin,.00001),(S.h-top-bottom)/Math.max(ymax-ymin,.00001)),tx=left+(S.w-left-right-(xmax-xmin)*scale)/2-xmin*scale,ty=top+(S.h-top-bottom-(ymax-ymin)*scale)/2-ymin*scale;S.projection={scale,tx,ty};S.base=[];const colors=regionColors(S.geo);$('shapes').innerHTML='';S.geo.forEach((f,i)=>{const rings=projected[i].map(r=>r.map(p=>[p[0]*scale+tx,p[1]*scale+ty]));const path=rings.map(r=>'M'+r.map(p=>p.map(x=>x.toFixed(2)).join(',')).join('L')+'Z').join('');const el=E('path',{d:path,fill:colors[i],stroke:'#7895a5','stroke-width':.75,'fill-rule':'evenodd','vector-effect':'non-scaling-stroke',class:'region','data-i':i,'data-id':f.id,tabindex:f.name?'0':'-1',role:f.name?'button':'presentation','aria-label':f.name?f.name+'，'+(best(f).u||'高校数据待补'):'南海诸岛边界'});if(!f.name){el.setAttribute('fill','#668594');el.style.pointerEvents='none';}if(nation&&!f.name)el.style.display='none';$('shapes').append(el);let cp=project(labelPoint(f));let area=rings.reduce((s,r)=>s+polygonArea(r),0);S.base.push({f,cp:[cp[0]*scale+tx,cp[1]*scale+ty],area,rings,el});});drawInset(nation);applyTransform();}
function drawInset(show){const g=$('inset');g.innerHTML='';if(!show)return;const w=S.w<560?60:100,h=S.w<560?86:142,x=S.w-w-(S.w<560?12:72),y=S.h-h-(S.w<560?86:66);g.append(E('rect',{x,y,width:w,height:h,rx:2,fill:'#e3f0f4',stroke:'#9bb1bb','stroke-width':.8}));g.append(E('text',{x:x+w/2,y:y+15,'text-anchor':'middle',fill:'#698793','font-size':9},'南海诸岛'));const px=lon=>x+8+(lon-105)/21*(w-16),py=lat=>y+22+(24-lat)/22*(h-28);for(const f of S.geo){const rs=f.rings.filter(r=>r.some(p=>p[0]>=105&&p[0]<=126&&p[1]<23)&&r.every(p=>p[1]<25));if(!rs.length)continue;const path=rs.map(r=>'M'+r.map(p=>px(p[0]).toFixed(2)+','+py(p[1]).toFixed(2)).join('L')+'Z').join('');g.append(E('path',{d:path,fill:f.name?'#c8d8bc':'#748e98',stroke:'#78919b','stroke-width':.55,'fill-rule':'evenodd'}));}S.insetBox={l:x-4,t:y-4,r:x+w+4,b:y+h+4};}
function applyTransform(){$('shapes').setAttribute('transform',`translate(${S.x} ${S.y}) scale(${S.z})`);cancelAnimationFrame(drawFrame);drawFrame=requestAnimationFrame(drawLabels);$('zoomInfo').textContent=Math.round(S.z*100)+'% · 字体随缩放变化';}
const measure=document.createElement('canvas').getContext('2d');function textWidth(s,fs,weight=700){measure.font=`${weight} ${fs}px "Microsoft YaHei","Noto Sans CJK SC",sans-serif`;return measure.measureText(s).width;}
function wrap(s,n){if(s.length<=n)return[s];const result=[];for(let i=0;i<s.length;i+=n)result.push(s.slice(i,i+n));return result;}
function drawLabels(){const g=$('labelLayer');g.innerHTML='';const nation=current().kind==='country',font=Math.max(8,Math.min(24,(nation?11.3:12.7)*Number($('fontSize').value)/100*Math.pow(S.z,.38))),avoid=$('avoid').checked,accepted=[];if(nation&&S.insetBox)accepted.push(S.insetBox);const controlRect=document.querySelector('.mapcontrols').getBoundingClientRect(),mapRect=$('map').getBoundingClientRect();accepted.push({l:controlRect.left-mapRect.left-3,r:controlRect.right-mapRect.left+3,t:controlRect.top-mapRect.top-3,b:controlRect.bottom-mapRect.top+3});const items=S.base.filter(b=>b.f.name).map(b=>({...b,best:best(b.f)})).sort((a,b)=>Number(!!b.best.u)-Number(!!a.best.u)||b.area-a.area);let shown=0;S.labels=[];for(const b of items){const x=b.cp[0]*S.z+S.x,y=b.cp[1]*S.z+S.y;if(x<-100||y<-100||x>S.w+100||y>S.h+100)continue;const names=wrap(nation?short(b.f.name):b.f.name,11),us=$('showUni').checked&&b.best.u?wrap(b.best.u,nation?8:10):[],lines=names.map(t=>({t,fs:font*.91,c:'#274b5a',w:650})).concat(us.map(t=>({t,fs:font,c:'#c62d28',w:800})));const width=Math.max(...lines.map(l=>textWidth(l.t,l.fs,l.w)))+9,height=lines.length*font*1.27+5;let offsets=[[0,0],[0,-17],[0,17],[-25,0],[25,0],[0,-34],[0,34],[-45,-22],[45,-22],[-45,22],[45,22],[-68,0],[68,0]];if(S.z>1.6)offsets=offsets.slice(0,7);let chosen=null;for(const[dx,dy]of offsets){const box={l:x+dx-width/2,r:x+dx+width/2,t:y+dy-height/2,b:y+dy+height/2};if(box.l<4||box.r>S.w-4||box.t<112||box.b>S.h-37)continue;if(!avoid||!accepted.some(a=>!(box.r+3<a.l||box.l-3>a.r||box.b+3<a.t||box.t-3>a.b))){chosen={...box,dx,dy};break;}}if(!chosen)continue;accepted.push(chosen);S.labels.push(chosen);shown++;if(Math.abs(chosen.dx)+Math.abs(chosen.dy)>20){g.append(E('line',{x1:x,y1:y,x2:x+chosen.dx,y2:y+chosen.dy,stroke:'#648896','stroke-width':.65,opacity:.75}));g.append(E('circle',{cx:x,cy:y,r:1.8,fill:'#648896'}));}const group=E('g',{'data-label-id':b.f.id});lines.forEach((l,i)=>group.append(E('text',{x:x+chosen.dx,y:y+chosen.dy-height/2+font*1.08+i*font*1.27,'text-anchor':'middle','font-size':l.fs.toFixed(2),'font-weight':l.w,'font-family':'"PingFang SC","Microsoft YaHei","Noto Sans CJK SC",sans-serif',fill:l.c,stroke:'#ffffff','stroke-width':us.length?2.8:2.2,'stroke-linejoin':'round','paint-order':'stroke fill'},l.t)));g.append(group);}if(current().kind==='district')drawCampusPins(g);S.labelCount=shown;}
function zoom(z,cx=S.w/2,cy=S.h/2){z=Math.max(.65,Math.min(24,z));const k=z/S.z;S.x=cx-(cx-S.x)*k;S.y=cy-(cy-S.y)*k;S.z=z;applyTransform();}
function highlight(id){hoverId=id;for(const b of S.base)b.el.classList.toggle('hover',b.f.id===id);}
function hideTip(){$('tooltip').style.display='none';highlight(null);}
function showTip(e,f){const b=best(f),t=$('tooltip');t.innerHTML=`<strong>${esc(f.name)}</strong><br>${esc(b.u||'高校 / 校区数据待补')}<br><span style="opacity:.75">${esc(b.meta)}</span>`;t.style.display='block';const r=$('map').getBoundingClientRect();t.style.left=Math.max(5,Math.min(r.width-t.offsetWidth-8,e.clientX-r.left+15))+'px';t.style.top=Math.max(7,Math.min(r.height-t.offsetHeight-8,e.clientY-r.top+15))+'px';highlight(f.id);}
const pointers=new Map();let drag=null,pinch=null,moved=false,tapFeature=null;
$('map').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const el=e.target.closest('[data-i]');if(el){e.preventDefault();enter(S.geo[Number(el.dataset.i)]);}}});
$('map').addEventListener('wheel',e=>{e.preventDefault();const r=$('map').getBoundingClientRect();zoom(S.z*Math.exp(-e.deltaY*.0016),e.clientX-r.left,e.clientY-r.top);hideTip();},{passive:false});
$('map').addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;pointers.set(e.pointerId,[e.clientX,e.clientY]);$('map').setPointerCapture(e.pointerId);if(pointers.size===1){drag={cx:e.clientX,cy:e.clientY,x:S.x,y:S.y};moved=false;const el=e.target.closest('[data-i]');tapFeature=el?S.geo[Number(el.dataset.i)]:null;}if(pointers.size===2){const[a,b]=[...pointers.values()],r=$('map').getBoundingClientRect();pinch={d:Math.hypot(a[0]-b[0],a[1]-b[1]),z:S.z,cx:(a[0]+b[0])/2-r.left,cy:(a[1]+b[1])/2-r.top,x:S.x,y:S.y};moved=true;} });
$('map').addEventListener('pointermove',e=>{if(pointers.has(e.pointerId))pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size>=2&&pinch){const[a,b]=[...pointers.values()],r=$('map').getBoundingClientRect(),d=Math.hypot(a[0]-b[0],a[1]-b[1]);S.z=Math.max(.65,Math.min(24,pinch.z*d/Math.max(pinch.d,1)));S.x=(a[0]+b[0])/2-r.left-(pinch.cx-pinch.x)*S.z/pinch.z;S.y=(a[1]+b[1])/2-r.top-(pinch.cy-pinch.y)*S.z/pinch.z;applyTransform();hideTip();return;}if(drag&&pointers.size){if(Math.hypot(e.clientX-drag.cx,e.clientY-drag.cy)>4)moved=true;if(moved){S.x=drag.x+e.clientX-drag.cx;S.y=drag.y+e.clientY-drag.cy;$('map').classList.add('drag');applyTransform();hideTip();}return;}const el=e.target.closest('[data-i]');if(el)showTip(e,S.geo[Number(el.dataset.i)]);else hideTip();});
function endPointer(e,cancel=false){const wasMoved=moved,tf=tapFeature;pointers.delete(e.pointerId);try{$('map').releasePointerCapture(e.pointerId);}catch(_){}if(!pointers.size){drag=pinch=null;tapFeature=null;$('map').classList.remove('drag');if(!wasMoved&&!cancel&&tf)enter(tf);}else{moved=true;pinch=null;const p=[...pointers.values()][0];drag={cx:p[0],cy:p[1],x:S.x,y:S.y};}}
$('map').addEventListener('pointerup',e=>endPointer(e));$('map').addEventListener('pointercancel',e=>endPointer(e,true));$('map').addEventListener('pointerleave',()=>{if(!pointers.size)hideTip();});
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function makeSVG(){const svg=$('map').cloneNode(true);svg.setAttribute('width',S.w);svg.setAttribute('height',S.h);svg.removeAttribute('id');svg.insertBefore(E('rect',{x:0,y:0,width:S.w,height:S.h,fill:'#dceef3'}),svg.firstChild);svg.append(E('text',{x:20,y:33,'font-size':21,'font-weight':800,fill:'#244451','font-family':'"Microsoft YaHei",sans-serif'},$('mapTitle').textContent));svg.append(E('text',{x:20,y:S.h-15,'font-size':10,fill:'#698391'},'高校参考名单 · 校区数据未完整核验 · 边界按源数据快照'));return new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'});}
$('svgBtn').onclick=()=>downloadBlob(makeSVG(),'高校地图_'+current().name+'.svg');$('pngBtn').onclick=()=>{const blob=makeSVG(),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=Math.round(S.w*2);c.height=Math.round(S.h*2);const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(b=>downloadBlob(b,'高校地图_'+current().name+'.png'),'image/png');};img.onerror=()=>{URL.revokeObjectURL(url);toast('PNG 导出失败，可使用 SVG 导出。');};img.src=url;};
$('dataBtn').onclick=()=>$('dataDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('backBtn').onclick=back;$('zoomIn').onclick=()=>zoom(S.z*1.3);$('zoomOut').onclick=()=>zoom(S.z/1.3);$('fitBtn').onclick=()=>{S.z=1;S.x=S.y=0;applyTransform();};$('fullBtn').onclick=()=>{document.body.classList.toggle('fullscreen');setTimeout(()=>drawMap(true),30);};$('showUni').onchange=drawLabels;$('avoid').onchange=drawLabels;$('fontSize').oninput=drawLabels;$('search').oninput=search;$('clearSearch').onclick=()=>{$('search').value='';search();};document.addEventListener('click',e=>{if(!e.target.closest('.searchwrap'))$('searchresults').style.display='none';});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('searchresults').style.display='none';if(document.body.classList.contains('fullscreen')){document.body.classList.remove('fullscreen');drawMap(true);}}if(e.key==='Backspace'&&e.target.tagName!=='INPUT'){e.preventDefault();back();}});
new ResizeObserver(()=>{if(S.geo.length)drawMap(true);}).observe($('map'));
// Source-tagged entity/campus indexes. No network code is used by this build.
const UIX=new Map(),CIX=new Map(),UM=new Map(),RID=new Map();let sourceMode='all';
const keyOf=(p,c='',d='')=>[p,c,d].join('|');
function buildIndexes(){for(const u of D.universities||[]){UM.set(u.id,u);for(const k of new Set([keyOf(u.p),keyOf(u.p,u.c),...(u.d?[keyOf(u.p,u.c,u.d)]:[])])){if(!UIX.has(k))UIX.set(k,[]);UIX.get(k).push(u);}}for(const r of D.campuses){for(const k of new Set([keyOf(r.p),keyOf(r.p,r.c),keyOf(r.p,r.c,r.d)])){if(!CIX.has(k))CIX.set(k,[]);CIX.get(k).push(r);}}for(const [id,n]of Object.entries(D.regions||{}))RID.set(keyOf(n.p,n.c,n.d),id);}
function allowed(u){return $('includeAdult').checked||u.level!=='成人';}
function priority(u){return [u.level==='本科'?0:u.level==='专科'?1:2,(u.tags||[]).includes('985')?0:(u.tags||[]).includes('211')?1:(u.tags||[]).includes('双一流')?2:3,Number.isFinite(Number(u.rank))?Number(u.rank):999999,u.private?1:0];}
function compareU(a,b){a=UM.get(a.uid)||a;b=UM.get(b.uid)||b;const x=priority(a),y=priority(b);for(let i=0;i<x.length;i++)if(x[i]!==y[i])return x[i]-y[i];return a.u.localeCompare(b.u,'zh-CN');}
function campusRows(p,c,d){return(CIX.get(keyOf(p,c||'',d||''))||[]).filter(r=>allowed(r)&&(!$('onlyOfficial').checked||r.verified)).slice().sort(compareU);}
function schoolRows(p,c='',d=''){const map=new Map(),cr=campusRows(p,c,d);for(const u of UIX.get(keyOf(p,c,d))||[])if(allowed(u))map.set(u.id,{...u,campuses:[],branch:false});for(const r of cr){if(!d&&!$('includeBranch').checked&&!map.has(r.uid))continue;const u=UM.get(r.uid);if(!u)continue;if(!map.has(u.id))map.set(u.id,{...u,campuses:[],branch:!d&&(u.p!==p||!!c&&u.c!==c)});map.get(u.id).campuses.push(r);}return[...map.values()].sort(compareU);}
function rawRank(u){const r=u.rankLabel||'';return r?(/^[0-9]+$/.test(r)?'2026软科主榜 '+r:'2026软科分类标签 '+r):'无可用排名：仅作候选展示';}
function best(f,node=current()){const l=locationFor(f,node),isP=node.kind==='country';let rs;
if(isP)rs=(UIX.get(keyOf(f.name))||[]).filter(allowed).slice().sort(compareU);else rs=schoolRows(l.p,l.c,(node.kind==='city'&&node.noChildren)?'':l.d);
if(rs.length){const u=rs[0],cp=u.campuses?.[0];return{u:u.u,uid:u.id,level:u.level,meta:[u.level,u.level==='专科'?'专科兜底':'',rawRank(u),cp?(cp.verified?'有官网校区依据':'位置来自历史POI，待复核'):'名录所在地',u.branch?'异地校区':''].filter(Boolean).join(' · '),sample:!!cp,campus:cp,count:rs.length,uncertain:!!cp&&!cp.verified};}
if(isP&&D.provinceBest[f.name])return{u:D.provinceBest[f.name],meta:'沿用参考标签；港澳台名录尚未完整纳入',count:0,sample:false};return{u:'',meta:l.d?'校区尚未匹配；不代表当地没有高校':'当前口径未匹配学校；不代表当地没有高校',count:0,sample:false};}
async function getMap(id,unpack=true){id=String(id);if(!CACHE[id])throw Error('该层级不在本源边界快照中；不会联网或绘制假边界');return unpack?CACHE[id].map(feature):CACHE[id];}
function updateCacheStatus(){const st=D.stats||{};$('cacheStatus').textContent=`完全离线 · ${Object.keys(CACHE).length} 份边界 · ${st.ordinarySchools||0} 所普通高校 · ${D.campuses.length} 条校区/办学地点`;$('factGeo').textContent=Object.keys(CACHE).length;$('factCity').textContent=st.ordinarySchools||0;$('factCampus').textContent=D.campuses.length;$('modeBadge').textContent='边界 + 数据已内嵌';$('packBtn').textContent='覆盖统计';}
async function renderView(){const node=current();S.loading=true;hideTip();$('mapToast').style.display='none';updateCrumb();S.z=1;S.x=S.y=0;try{if(node.kind==='district'||node.noChildren){S.geo=[node.f];}else if(!CACHE[node.id]&&node.f){S.geo=[node.f];node.noChildren=true;}else S.geo=await getMap(node.id);renderSidebar();drawMap(true);}catch(e){S.geo=node.f?[node.f]:[];renderSidebar();drawMap(true);toast(e.message,5000);}S.loading=false;updateCacheStatus();}
function updateCrumb(){$('crumb').innerHTML='';S.stack.forEach((v,i)=>{if(i)$('crumb').append(document.createTextNode(' › '));const b=document.createElement(i===S.stack.length-1?'b':'button');b.textContent=v.name;if(i<S.stack.length-1)b.onclick=()=>{S.stack=S.stack.slice(0,i+1);renderView();};$('crumb').append(b);});const v=current();$('mapTitle').textContent=v.kind==='country'?'各省最佳高校 · 参考':v.kind==='district'?v.name+' · 高校与校区':v.name+' · '+(v.kind==='province'&&!['北京市','天津市','上海市','重庆市','香港特别行政区','澳门特别行政区'].includes(v.p)?'各市':'各县区')+'最佳高校 · 参考';$('mapSubtitle').textContent=v.kind==='district'?'按具体校区归属展示；同一大学可出现在不同县区。':'点击色块下钻 · 拖动平移 · 缩放时文字同步调整并避让';$('backBtn').disabled=S.stack.length===1;}
function campusHTML(r){return `<div class="campusrow"><strong>${esc(r.campus)}</strong><span class="quality ${r.verified?'verified':''}">${r.verified?'官网校区依据':'历史位置候选'}</span><p>${esc([r.p,r.c,r.d].filter(Boolean).join(' / '))}</p><p>${esc(r.address||'源记录未附详细地址')}</p><p>${esc(r.status||'')}<br>${Number.isFinite(r.lng)?'有POI坐标（转换至GCJ-02）':'未设坐标，不绘制伪点位'}</p><a href="${esc(r.sourceUrl||D.sources[2].url)}" target="_blank" rel="noopener noreferrer">来源（联网时查看） ↗</a></div>`;}
function universityHTML(u){return `<div class="rname">${esc(u.level)} ${(u.tags||[]).map(t=>'<span class="chip">'+esc(t)+'</span>').join('')} ${u.branch?'<span class="quality">异地校区</span>':''}</div><div class="runi">${esc(u.u)}</div><div class="rmeta">${esc(rawRank(u))}<br>${esc(u.source||'学校整体资料')} · 名录所在地：${esc(u.hostRaw||u.c||u.p)}</div>`;}
function showSchool(id){const u=UM.get(id);if(!u)return;const rs=D.campuses.filter(r=>r.uid===id);$('schoolTitle').textContent=u.u;$('schoolBody').innerHTML=universityHTML(u)+`<div class="callout">${rs.length} 条已收录校区/办学地点。学校整体排名不代表每个校区的招生分数或教学质量。历史POI未经逐一办学状态复核。</div>`+(rs.length?rs.map(campusHTML).join(''):'<div class="empty">学校主体已在名录中，具体校区尚未匹配。不会把学校登记城市当作某个县区或精确地址。</div>');$('schoolDialog').showModal();}
function renderSidebar(){const v=current(),fs=S.geo.filter(f=>f.name),detail=v.kind==='district'||v.noChildren,list=$('list');list.innerHTML='';list.scrollTop=0;$('sideTitle').textContent=v.name+(detail?' · 学校与校区':' · 下属行政区');$('sideDesc').textContent=detail?'按学校去重，展开保留全部校区。位置数据与学校名录来源分开标注。':'全部行政区保留在此；地图隐藏部分文字仅为避免遮挡。';
if(detail){const rs=schoolRows(v.p,v.c,v.kind==='district'?v.d:''),cr=campusRows(v.p,v.c,v.kind==='district'?v.d:'');$('sideCount').textContent=`${rs.length} 所候选学校 · ${cr.length} 条办学地点`;
if(v.noChildren){const e=document.createElement('div');e.className='callout';e.textContent=v.id==='710000'?'本源只有台湾省轮廓，未取得市县细分；不伪造行政区。港澳台高校尚未完整纳入。':'本源没有普通县区细分轮廓，保留真实本级地图与全市学校。';list.append(e);}
if(!rs.length){const e=document.createElement('div');e.className='empty';e.innerHTML='尚未匹配到校区记录<br><small>这不等于当地没有高校。<br>学校主体可以已收录，但缺少可定位的校区资料。</small>';list.append(e);}
for(const u of rs){const el=document.createElement('details');el.className='schoolcard';el.open=rs.length<=3;el.innerHTML=`<summary>${universityHTML(u)}<div class="rmeta">本区 ${u.campuses.length} 条校区/办学地点 · 点击展开</div></summary>${u.campuses.length?u.campuses.map(campusHTML).join(''):'<div class="campusrow">仅有名录所在地；具体地址未匹配。</div>'}`;const b=document.createElement('button');b.className='schoolmore';b.textContent='查看该校全部已收录校区';b.onclick=()=>showSchool(u.id);el.append(b);list.append(el);}return;}
$('sideCount').textContent=`${fs.length} 个地区 · ${fs.filter(f=>best(f).u).length} 个有候选高校`;
fs.forEach((f,i)=>{const b=best(f),el=document.createElement('button');el.className='item';el.dataset.id=f.id;el.innerHTML=`<span class="ordinal">${String(i+1).padStart(2,'0')}</span><div><div class="rname">${esc(f.name)} ${b.level==='专科'?'<span class="chip">专科兜底</span>':''}</div><div class="runi ${b.u?'':'emptyuni'}">${esc(b.u||'校区尚未匹配')}</div><div class="rmeta">${esc(b.meta)}${b.count?' · '+b.count+' 所候选':''}</div></div><span class="arrow">›</span>`;el.onclick=()=>enter(f);el.onpointerenter=()=>highlight(f.id);el.onpointerleave=()=>highlight(null);list.append(el);});}
function createSearchIndex(){searchIndex=[];for(const[id,n]of Object.entries(D.regions||{})){searchIndex.push({label:n.name,school:'',...n,id,type:'地区'});}for(const u of D.universities||[]){searchIndex.push({label:u.u,school:rawRank(u),p:u.p,c:u.c,d:u.d||'',uid:u.id,id:RID.get(keyOf(u.p,u.c,u.d))||RID.get(keyOf(u.p,u.c))||RID.get(keyOf(u.p)),type:'学校'});}for(const r of D.campuses){searchIndex.push({label:r.u+' · '+r.campus,school:r.d,p:r.p,c:r.c,d:r.d,id:RID.get(keyOf(r.p,r.c,r.d))||RID.get(keyOf(r.p,r.c))||RID.get(keyOf(r.p)),type:'校区'});}}
function search(){let q=$('search').value.trim().toLowerCase();const box=$('searchresults');box.innerHTML='';if(!q){box.style.display='none';return;}const aliases={'浙大':'浙江大学','北大':'北京大学','清华':'清华大学','中科大':'中国科学技术大学','哈工大':'哈尔滨工业大学','合工大':'合肥工业大学'};q=aliases[q]||q;const hits=searchIndex.filter(r=>(r.label+' '+r.school+' '+r.p+' '+r.c+' '+r.d).toLowerCase().includes(q)).sort((a,b)=>(a.label===q?0:a.type==='学校'?1:2)-(b.label===q?0:b.type==='学校'?1:2)).slice(0,60);if(!hits.length)box.innerHTML='<div class="empty">当前内嵌资料没有匹配结果。</div>';for(const r of hits){const el=document.createElement('button');el.className='searchitem';el.innerHTML=`<span class="quality">${r.type}</span> <b>${esc(r.label)}</b><small>${esc([r.p,r.c,r.d].filter(Boolean).join(' / '))}</small>`;el.onclick=async()=>{$('searchresults').style.display='none';$('search').value='';if(r.id)await navigateID(r.id);if(r.uid)showSchool(r.uid);};box.append(el);}box.style.display='block';}
async function navigateID(id){const path=[];while(id&&id!=='100000'){const n=D.regions[id];if(!n)break;path.unshift(n);id=n.parent;}S.stack=[root];for(const n of path){const f=(CACHE[n.parent]||[]).map(feature).find(f=>f.id===n.id);if(!f)break;const kind=!n.c?'province':n.d?'district':'city';S.stack.push({id:n.id,name:n.name,kind,p:n.p,c:n.c,d:n.d,f,noChildren:kind==='city'&&!CACHE[n.id]});}await renderView();}
function drawCampusPins(g){const v=current(),rs=campusRows(v.p,v.c,v.d);for(const r of rs){if(!Number.isFinite(r.lng)||!Number.isFinite(r.lat))continue;const p=project([r.lng,r.lat]),x=(p[0]*S.projection.scale+S.projection.tx)*S.z+S.x,y=(p[1]*S.projection.scale+S.projection.ty)*S.z+S.y;if(x<0||y<112||x>S.w||y>S.h-37)continue;const c=E('circle',{cx:x,cy:y,r:4.5+Math.min(2,S.z*.2),fill:r.verified?'#147b63':'#d78930',stroke:'#fff','stroke-width':1.8,style:'pointer-events:all;cursor:pointer'});c.append(E('title',{},r.u+' · '+r.campus+'\n'+r.status));c.addEventListener('click',e=>{e.stopPropagation();showSchool(r.uid);});g.append(c);}}
function showCoverage(){const st=D.stats;$('coverageMeta').innerHTML=`<div class="datafacts"><div><b>${st.ordinarySchools}</b>普通高校主体</div><div><b>${st.campusRecords}</b>校区/办学地点记录</div><div><b>${st.districtsWithCampuses}</b>已匹配县区</div></div><p>名录：本科 ${st.bachelorSchools} 所、专科 ${st.vocationalSchools} 所；另内嵌成人高校 ${st.adultSchools} 所（默认不参与普通高校优选）。</p><p><b>学校主体完整收录不等于校区完整。</b>${st.schoolsWithCampuses} 所学校匹配到位置记录；${st.officialCampusAssociations} 条校区关联有本轮官网核对依据，其余为历史POI候选。底图已内嵌 ${st.boundaryFiles} 份边界，含 ${st.districtPolygons} 个县区/等效轮廓。</p>`;$('coverageTable').innerHTML='<tr><th>地区</th><th>普通高校</th><th>地点记录</th><th>县区覆盖</th></tr>'+D.coverage.map(r=>`<tr><td>${esc(r.province)}</td><td>${r.schools}</td><td>${r.campuses}</td><td>${r.districts} / ${r.allDistricts}</td></tr>`).join('');$('coverageDialog').showModal();}
function exportData(){const v=current(),rs=v.kind==='country'?D.campuses:campusRows(v.p,v.c,v.d);downloadBlob(new Blob([JSON.stringify({location:v.name,universities:v.kind==='country'?D.universities:schoolRows(v.p,v.c,v.d),campuses:rs,sources:D.sources},null,2)],{type:'application/json;charset=utf-8'}),'高校数据_'+v.name+'.json');}
async function selfTest(){const fail=[],checks=[];let polys=0;for(const[id,a]of Object.entries(CACHE)){try{const fs=a.map(feature);if(!fs.length)fail.push('empty '+id);for(const f of fs){if(f.name&&!f.rings.length)fail.push('no rings '+id+f.name);if(f.rings.some(r=>r.some(p=>!Number.isFinite(p[0])||!Number.isFinite(p[1]))))fail.push('coordinates '+id);polys++;}}catch(e){fail.push(id+e.message);}}for(const r of D.campuses)if(!UM.has(r.uid))fail.push('orphan '+r.id);for(const id of ['110000','110108','330000','330100','330106','340000','341800','341802','440000','440300','440305','510000','510100','540000','650000','810000','820000']){if(!D.regions[id])continue;try{await navigateID(id);drawLabels();if(!S.geo.length||!document.querySelector('#shapes path'))fail.push('render '+id);const b=S.labels;for(let i=0;i<b.length;i++)for(let j=i+1;j<b.length;j++)if(!(b[i].r<=b[j].l||b[i].l>=b[j].r||b[i].b<=b[j].t||b[i].t>=b[j].b))fail.push('overlap '+id);checks.push(id);}catch(e){fail.push(id+e.message);}}S.stack=[root];await renderView();drawLabels();const before=Number(document.querySelector('#labelLayer text')?.getAttribute('font-size'));zoom(2);drawLabels();const after=Number(document.querySelector('#labelLayer text')?.getAttribute('font-size'));if(!(after>before))fail.push('font scaling');zoom(1);S.x=S.y=0;applyTransform();const result={pass:!fail.length,errors:fail,offline:true,boundaryFiles:Object.keys(CACHE).length,features:polys,renderedNavigation:checks,fontBefore:before,fontAfter:after,schoolEntities:D.universities.length,campusRecords:D.campuses.length};window.__testResult=result;const pre=document.createElement('pre');pre.id='selftestResult';pre.style.display='none';pre.textContent=JSON.stringify(result);document.body.append(pre);document.body.dataset.testStatus=result.pass?'passed':'failed';return result;}
async function boot(){try{const b=Uint8Array.from(atob($('geoData').textContent.trim()),c=>c.charCodeAt(0));CACHE=JSON.parse(await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip'))).text());buildIndexes();createSearchIndex();for(const id of ['includeBranch','includeAdult','onlyOfficial'])$(id).onchange=()=>{renderSidebar();drawLabels();};$('packBtn').onclick=showCoverage;$('exportData').onclick=exportData;$('sourceList').innerHTML=D.sources.map(s=>'<p><b>'+esc(s.name)+'</b><br>'+esc(s.note)+'<br><a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">查看来源 ↗</a></p>').join('');await renderView();window.__atlas={S,D,CACHE,enter,back,renderView,zoom,drawLabels,navigateID,showCoverage,schoolRows,campusRows,selfTest};if(location.hash==='#selftest')await selfTest();else if(location.hash.startsWith('#region='))await navigateID(location.hash.slice(8));}catch(e){toast('打开失败：'+e.message,0);$('cacheStatus').textContent=e.message;}}

// V5: distinguish current third-party address snapshots from historical POI and official evidence.
function quality(r){return r.verified?'官网校区依据':r.sourceKind==='profile'?'本轮院校档案 · 待官网核验':'历史位置 · 待复核';}
function compareCampus(a,b){return compareU(a,b)||({official:0,profile:1,historical:2}[a.sourceKind]??3)-({official:0,profile:1,historical:2}[b.sourceKind]??3);}
function campusRows(p,c,d){return(CIX.get(keyOf(p,c||'',d||''))||[]).filter(r=>allowed(r)&&(!$('onlyOfficial').checked||r.verified)).slice().sort(compareCampus);}
function campusHTML(r){const position=Number.isFinite(r.lng)?(r.coordinateStatus||'历史POI坐标（转换至GCJ-02，非本轮实测）'):'未设精确坐标，不绘制伪点位';return `<div class="campusrow"><strong>${esc(r.campus)}</strong><span class="quality ${r.verified?'verified':r.sourceKind==='profile'?'profile':''}">${quality(r)}</span><p>${esc([r.p,r.c,r.d].filter(Boolean).join(' / '))}${!r.d?' · 县区待核':''}</p><p>${esc(r.address||'未提供详细门牌')}</p>${r.notes?'<p><b>说明：</b>'+esc(r.notes)+'</p>':''}<p>${esc(r.status||'')}<br>${esc(position)}${r.retrievedAt||r.verifiedAt?'<br>本轮读取/核对：'+esc(r.verifiedAt||r.retrievedAt):''}</p><a href="${esc(r.sourceUrl||D.sources[2].url)}" target="_blank" rel="noopener noreferrer">${esc(r.source||'来源')}（联网时查看） ↗</a>${r.evidence?.length?'<details><summary>其他来源 / 合并记录（'+r.evidence.length+'）</summary>'+r.evidence.map(e=>'<p>'+esc(e.source)+'：'+esc(e.address)+'<br>'+esc(e.note||'同一地点的附加来源')+'</p>').join('')+'</details>':''}</div>`;}
function best(f,node=current()){const l=locationFor(f,node),isP=node.kind==='country';let rs;if(isP)rs=(UIX.get(keyOf(f.name))||[]).filter(allowed).slice().sort(compareU);else rs=schoolRows(l.p,l.c,(node.kind==='city'&&node.noChildren)?'':l.d);if(rs.length){const u=rs[0],cp=u.campuses?.[0];return{u:u.u,uid:u.id,level:u.level,meta:[u.level,u.level==='专科'?'专科补位':'',rawRank(u),cp?quality(cp):'名录所在地',u.branch?'异地校区':''].filter(Boolean).join(' · '),sample:!!cp,campus:cp,count:rs.length,uncertain:!!cp&&!cp.verified};}if(isP&&D.provinceBest[f.name])return{u:D.provinceBest[f.name],meta:'沿用参考标签；港澳台名录尚未系统纳入',count:0,sample:false};return{u:'',meta:l.d?'校区尚未匹配；不代表当地没有高校':'当前口径未匹配学校；不代表当地没有高校',count:0,sample:false};}
function showSchool(id){const u=UM.get(id);if(!u)return;const rs=D.campuses.filter(r=>r.uid===id).sort(compareCampus);$('schoolTitle').textContent=u.u;$('schoolBody').innerHTML=universityHTML(u)+`<div class="callout">${rs.length} 条已收录校区/办学地点记录（不等同独立校园数）。学校整体排名不代表每个校区的招生分数或教学质量；本科机构分类也不代表该校区当年招收本科生。来源按官网核对、本轮第三方档案、历史POI分别标注。</div>`+(rs.length?rs.map(campusHTML).join(''):'<div class="empty">主体已收录，尚缺可确认的具体校园地址。已进入缺口清单，不使用县城中心坐标代替校园。</div>');$('schoolDialog').showModal();}
function downloadGaps(){downloadBlob(new Blob([JSON.stringify({version:D.revision.version,date:D.revision.date,missingSchools:D.missingSchools,locationHints:D.locationHints,unresolvedAddresses:D.unresolvedCampusAddresses,quarantinedRecords:D.quarantinedRecords,sources:D.sources},null,2)],{type:'application/json;charset=utf-8'}),'全国高校地图_v5_缺口与待核清单.json');}
function showCoverage(){const st=D.stats,b=D.revision.baseline;$('coverageMeta').innerHTML=`<div class="datafacts"><div><b>${st.ordinarySchoolsWithLocations} / ${st.ordinarySchools}</b>普通高校有地点关联</div><div><b>${st.campusRecords}</b>校区/办学地点记录</div><div><b>${st.districtsWithCampuses}</b>县区有地点记录</div></div><p><b>V5 · ${esc(D.revision.date)}</b>：地点记录由 ${b.campusRecords} 增至 ${st.campusRecords}，县区覆盖由 ${b.districtsWithCampuses} 增至 ${st.districtsWithCampuses}。本轮读取 ${st.profileRecordsFetched} 份同名院校档案，不把第三方数据标成官方核验。</p><p>当前记录来源：官网关联 ${st.officialLocationRecords} 条；本轮第三方院校档案 ${st.profileLocationRecords} 条；历史位置 ${st.historicalLocationRecords} 条。数量是来源整理后的地点记录数，不是已确认独立校园数。</p><p><b>剩余缺口：</b>${st.ordinarySchoolsWithoutLocations} 所普通高校仍无具体地点关联；另 ${st.ordinarySchoolsOnlyCityLocation} 所只定位到城市。${st.addressesToReview} 条地址或排除项需复核。县区无记录不能解读为当地没有高校。港澳台名录和台湾市县边界本轮未系统补齐。</p><button id="downloadGaps">导出缺口与待核清单</button><p>真实边界 ${st.boundaryFiles} 份已全部内嵌；断网也可浏览。学校主体与地图行政区划均依来源快照，不冒充实时资料。</p>`;$('coverageTable').innerHTML='<tr><th>地区</th><th>普通高校有地点</th><th>地点记录</th><th>县区覆盖</th></tr>'+D.coverage.map(r=>`<tr><td>${esc(r.province)}</td><td>${r.locatedSchools} / ${r.schools}</td><td>${r.campuses}</td><td>${r.districts} / ${r.allDistricts}</td></tr>`).join('');$('downloadGaps').onclick=downloadGaps;$('coverageDialog').showModal();}

boot();
